<a href="https://colab.research.google.com/github/YugPatel07/Machine-Learning/blob/main/Insurance_YUGP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv('/content/Insurance.csv')
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
data.shape

(1338, 7)

In [ ]:
data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [ ]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [ ]:
print(x)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,4,5])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 19 27.9 0]
 [0.0 1.0 1.0 ... 18 33.77 1]
 [0.0 1.0 1.0 ... 28 33.0 3]
 ...
 [1.0 0.0 1.0 ... 18 36.85 0]
 [1.0 0.0 1.0 ... 21 25.8 0]
 [1.0 0.0 0.0 ... 61 29.07 0]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred1=lin_reg.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred1))

0.7999876970680433


In [ ]:
print("Train Accuracy:",lin_reg.score(x_train, y_train))
print("Test Accuracy:",lin_reg.score(x_test, y_test))

Train Accuracy: 0.7370262574551634
Test Accuracy: 0.7999876970680433


In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(x_train)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, y_train)

LinearRegression()

In [ ]:
y_pred2 = lin_reg_2.predict(poly_reg.fit_transform(x_test))

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred2))

0.8512267615286189


In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator= lin_reg_2 , X=x_train, y=y_train, cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 72.64 %
Standard Deviation: 5.57 %


In [ ]:
from xgboost import XGBRegressor
reg = XGBRegressor()
reg.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [ ]:
y_pred3=reg.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred3))

0.8408953109107041


In [ ]:
y_pred1 = lin_reg.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test.reshape(len(y_test),1)),1))

In [ ]:
data[:50:5]

age     sex     bmi  children smoker     region      charges
0    19  female  27.900         0    yes  southwest  16884.92400
5    31  female  25.740         0     no  southeast   3756.62160
10   25    male  26.220         0     no  northeast   2721.32080
15   19    male  24.600         1     no  southwest   1837.23700
20   60  female  36.005         0     no  northeast  13228.84695
25   59  female  27.720         3     no  southeast  14001.13380
30   22    male  35.600         0    yes  southwest  35585.57600
35   19    male  20.425         0     no  northwest   1625.43375
40   24  female  26.600         0     no  northeast   3046.06200
45   55    male  37.300         0     no  southwest  20630.28351

In [ ]:
print(x[[0, 1, 3]])
#southwest, southeast, northwest

[[1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 19 27.9 0]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 18 33.77 1]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 0.0 33 22.705 0]]


In [ ]:
#CASE1:- Predict insurance for a 37 years old Male, BMI= 30 having 2 children & not a Smoker, living in northwest region
#actual charges = 6406

#CASE2:- Predict insurance for a 60 years old Female, BMI= 36 having 0 children & not a Smoker, living in northeast region
#actual charges = 13229
#FORMAT[sex, smoker, region, age, bmi, children]
#[male(01), female(10)]... [yes(01), no(10)]... [NE(1000), NW(0100), SE(0010), SW(0001)]

**CASE1**

Actual= 6406

In [ ]:
lin_reg.predict([[0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 37, 30, 2]])

array([8235.95])

In [ ]:
lin_reg_2.predict(poly_reg.fit_transform([[0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 37, 30, 2]]))

array([7839.71])

In [ ]:
reg.predict([[0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 37, 30, 2]])

array([7625.63], dtype=float32)

**CASE2**

Actual= 13229

In [ ]:
reg.predict([[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 60, 36, 0]])

array([13461.96], dtype=float32)

In [ ]:
lin_reg.predict([[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 60, 36, 0]])

array([15488.62])

In [ ]:
lin_reg_2.predict(poly_reg.fit_transform([[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 60, 36, 0]]))

array([15313.16])